### ISSUE TITLE
Add support for downloading from another workflow

### ISSUE THREAD

**Issue by rufusnufus** [ishworkh/docker-image-artifact-download#4]
Can you add support for downloading image artefact from another workflow from another repo? Something like in [action-download-artifact](https://github.com/dawidd6/action-download-artifact):

```yaml
- name: Download image
   uses: ishworkh/docker-image-artifact-download@v1
   with:
     image: "test_image:latest"
     workflow: workflow_name.yml
    # Optional, the status or conclusion of a completed workflow to search for
    # Can be one of a workflow conclusion:
    #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
    # Or a workflow status:
    #   "completed", "in_progress", "queued"
    workflow_conclusion: success
    # Optional, will get head commit SHA
    pr: ${{github.event.pull_request.number}}
    # Optional, defaults to current repo
    repo: ${{github.repository}}
```
